name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: try-docker-actions:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker run -rm try-docker-actions:latest
