name: Build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            usr-local-cargo-registry
            build-target
          key: cache-${{ hashFiles('Dockerfile') }}
      - uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "usr-local-cargo-registry": "/usr/local/cargo/registry",
              "build-target": "/build/target"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:test-image
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      packages: read
    services:
      my_service:
        image: ghcr.io/${{ github.repository }}:test-image
        ports:
          - 8081:8081
    steps:
      - run: curl localhost:8081
