name: Build docker image

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            usr-local-cargo-registry
            build-target
          key: cache-${{ hashFiles('Dockerfile') }}
      - uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "usr-local-cargo-registry": "/usr/local/cargo/registry",
              "build-target": "/build/target"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: try-docker-actions:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker image ls | grep try-docker-actions
      - run: docker run --rm try-docker-actions:latest
