name: Prune

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prune:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          container: try-docker-actions
          keep-last: 2
          prune-untagged: true
